// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCf8Bp3dlhThyFhZ9f7SVkVincaWXlfFE4',
    appId: '1:1025429456539:android:d1a627059d5c480794683e',
    messagingSenderId: '1025429456539',
    projectId: 'aptmatepro',
    storageBucket: 'aptmatepro.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmSsko-QCOLtwaePdQan7h2NwSl3tktWk',
    appId: '1:1025429456539:ios:d0d3ac57656fbe7c94683e',
    messagingSenderId: '1025429456539',
    projectId: 'aptmatepro',
    storageBucket: 'aptmatepro.firebasestorage.app',
    androidClientId: '1025429456539-0kbql5ogga1dg3k8e7vug0b3440ntvkg.apps.googleusercontent.com',
    iosClientId: '1025429456539-gjruhbsrlalpf5kebfsh9uj6b0imd2r7.apps.googleusercontent.com',
    iosBundleId: 'com.marwadiuniversity.smartsociety',
  );

}